version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/aws-codedeploy

permissions:
  - object: /home/ec2-user/aws-codedeploy
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
